Remove coming soon, add nornir plugin
nautobot/docs-landing-page pull request #2
Opened 2022-09-28 03:12 UTC by itdependsnetworks

2022-09-28 03:13 UTC, itdependsnetworks commented
Opening up the index file locally, I get 
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/9260483/192679142-952bdfde-5b63-4a0a-b2a8-d56e680db683.png">

2022-09-28 08:37 UTC, cmsirbu requested changes
Hey, thanks for the PR... would you please remove the "Network to Code Nautobot Apps" link as it's redundant with the big yellow button? I left it there until plugin-nornir was ready to go in (it's fine where it is now).

This also solves the need to have an empty row in the left hand side.

2022-09-28 08:55 UTC, cmsirbu requested changes

2022-09-28 08:55 UTC, cmsirbu commented on html/index.html
>                              <!-- <li class="list-group-item"><a
Please remove the commented section.

2022-09-28 08:55 UTC, cmsirbu commented on html/index.html
>                              <!-- <li class="list-group-item"><a
Please remove the commented section.

2022-09-30 01:06 UTC, itdependsnetworks commented
Updated view 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/9260483/193168328-79d796b4-4cec-440a-9a7a-74d73a35bd14.png">

2022-09-30 01:16 UTC, itdependsnetworks commented
Updated view again
<img width="814" alt="image" src="https://user-images.githubusercontent.com/9260483/193169142-46945b17-1754-4a6a-958c-bd3df15008be.png">

2022-09-30 09:38 UTC, cmsirbu commented on html/index.html
> +                            <li class="list-group-item"><a href="https://www.networktocode.com/nautobot/apps/"
This is a docs site and we should be linking to docs - I don't agree with this link change here. The main button sending ppl to the main website (that doesn't link to docs) is not the way. The https://docs.nautobot.com/projects/core/en/stable/apps/ page links to the ecosystem page right at the top if people want to discover more.

2022-09-30 12:41 UTC, cmsirbu approved these changes
LGTM, thank you!

2022-09-30 12:41 UTC, merged